"""Public document/runtime foundation for the MonkezCanva editor."""

from .clipboard import (
    CLIPBOARD_FORMAT,
    CLIPBOARD_VERSION,
    CANVAS_CLIPBOARD_MIME_TYPE,
    build_selection_payload,
    decode_selection_payload,
    remap_selection_payload,
)

from .models import (
    DOCUMENT_FORMAT,
    DOCUMENT_VERSION,
    CanvasDocument,
    ConnectorModel,
    ElementModel,
    GroupModel,
    PortModel,
    ResourceModel,
    SceneModel,
)
from .operations import OperationEvent
from .palette import (
    MAX_RECENT_COMPONENTS,
    PALETTE_FAVORITES_KEY,
    PALETTE_RECENT_KEY,
    PaletteEntry,
    normalize_component_ids,
    record_recent_component,
    search_palette,
)
from .persistence import (
    ASSET_MANIFEST_KEY,
    AssetIntegrityIssue,
    RecoveryLoadResult,
    atomic_write_json,
    backup_path,
    build_asset_manifest,
    load_json_with_recovery,
    sha256_file,
    verify_asset_manifest,
)
from .registry import (
    BUILTIN_ELEMENT_DEFINITIONS,
    ElementDefinition,
    ElementRegistry,
    create_default_element_registry,
)
from .schema import DOCUMENT_JSON_SCHEMA, DocumentMigrationResult, migrate_document
from .snapping import (
    SMART_GUIDES_KEY,
    SNAP_DISTANCE_KEY,
    SNAP_TARGETS,
    SNAP_TARGETS_KEY,
    SnapGuide,
    SnapRect,
    SnapResult,
    normalize_snap_targets,
    snap_rect,
)
from .routing import deduplicate_points, orthogonal_points, parallel_lane_offset

__all__ = [
    "CLIPBOARD_FORMAT",
    "CLIPBOARD_VERSION",
    "CANVAS_CLIPBOARD_MIME_TYPE",
    "MAX_RECENT_COMPONENTS",
    "PALETTE_FAVORITES_KEY",
    "PALETTE_RECENT_KEY",
    "DOCUMENT_FORMAT",
    "DOCUMENT_VERSION",
    "DOCUMENT_JSON_SCHEMA",
    "ASSET_MANIFEST_KEY",
    "SMART_GUIDES_KEY",
    "SNAP_DISTANCE_KEY",
    "SNAP_TARGETS",
    "SNAP_TARGETS_KEY",
    "AssetIntegrityIssue",
    "CanvasDocument",
    "BUILTIN_ELEMENT_DEFINITIONS",
    "ConnectorModel",
    "ElementModel",
    "ElementDefinition",
    "ElementRegistry",
    "GroupModel",
    "OperationEvent",
    "PaletteEntry",
    "RecoveryLoadResult",
    "PortModel",
    "ResourceModel",
    "SceneModel",
    "SnapGuide",
    "SnapRect",
    "SnapResult",
    "create_default_element_registry",
    "atomic_write_json",
    "backup_path",
    "build_selection_payload",
    "build_asset_manifest",
    "decode_selection_payload",
    "load_json_with_recovery",
    "migrate_document",
    "normalize_component_ids",
    "normalize_snap_targets",
    "deduplicate_points",
    "orthogonal_points",
    "parallel_lane_offset",
    "record_recent_component",
    "remap_selection_payload",
    "search_palette",
    "snap_rect",
    "DocumentMigrationResult",
    "sha256_file",
    "verify_asset_manifest",
]
